port: 9200
project: project-name
role_arn: aws-role-arn-with-ce-read-access
filter: |
  {
      "Not": {
          "Dimensions": {
              "Key": "RECORD_TYPE",
              "Values": [
                  "Credit",
                  "Enterprise Discount Program Discount"
              ]
          }
      }
  }